### ISSUE TITLE
Are there a new strategy to replace gen_*_*_*_parameters 

### ISSUE THREAD

**Issue by zhuqingliang** [intel/vaapi-fits#130]
When I try to add some new parameters to test, I need to add gen_*_*_*_variants and  gen_*_*_*_parameters  in lib/parameters.py , I think It's maybe too much redundancy code, maybe we can find a new way to pass parameters

**Comment by uartie** [comment]
Can you propose any design ideas/patches?

**Comment by zhuqingliang** [comment]
For now, I have no idea .Just a propose, may be it will also have big influences in baseline/full.default.

**Comment by zhuqingliang** [comment]
If you think It's not necessary, just close this issue.
