### ISSUE TITLE
enhancement: multi-resolution stream MD5 value calculation

### ISSUE THREAD

**Issue by wangzj0601** [intel/vaapi-fits#14]
we should support multi-resolution stream MD5 value calculation

**Comment by uartie** [comment]
AFAICT, ffmpeg and gstreamer decode will automatically scale each frame to the designated output resolution.  Thus, if input has 100 frames in multiple resolutions and output is specified as NxM resolution, then all 100 frames in the output will be NxM resolution.

Can you describe a case where we need multi-resolution support?

**Comment by wangzj0601** [comment]
same as https://github.com/intel/vaapi-fits/issues/15#issuecomment-467272942

**Comment by wangzj0601** [comment]
https://github.com/intel/vaapi-fits/pull/24 fix this issue

**Comment by wangzj0601** [comment]
now gstreamer add parse "videoscale" to make the output as single resolution, so no need multi-res ssim support, close it
