### ISSUE TITLE
[vaapi-fits][ffmpeg-qsv][HEVC 8k encode] cannot reshape array of size 0 into shape (4320,7680)

### ISSUE THREAD

**Issue by FocusLuo** [intel/vaapi-fits#140]
Stetps:
1, ffmpeg -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -v verbose -f rawvideo -pix_fmt yuv420p -s:v 7680x4320 -i /opt/media/src/assets/otc-media/yuv/Peru_8K_HDR_7680x4320_100frames_I420.yuv -vf 'format=nv12,hwupload=extra_hw_frames=120' -an -c:v hevc_qsv -profile:v main -g 30 -q 28 -preset 1 -slices 1 -bf 2 -low_power 0 -vframes 50 -y test_8k.h265
2,  ffmpeg -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -v verbose -c:v hevc_qsv -i test_8k.h265 -vf 'hwdownload,format=nv12' -pix_fmt yuv420p -f rawvideo -vsync passthrough -vframes 50 -y  test_8k.yuv
3, check_psnr:  get_media().baseline.check_psnr

Error Log info:
[2019-11-19 06:56:26.810025] INFO: slash:   Total: 50 packets (5311738 bytes) demuxed
[2019-11-19 06:56:26.810155] INFO: slash: Output file #0 (/opt/media/test-results/vaapi-fits/encode/hevc/2c9a5ff8-0a95-11ea-961b-0242ac120002_0/_0.test.ffmpeg-qsv.encode.hevc/cqp/Peru_8K_HDR_7680x4320_100frames-cqp-main-30-28-1-1-2-0-7680x4320-I420.yuv):
[2019-11-19 06:56:26.810249] INFO: slash:   Output stream #0:0 (video): 34 frames encoded; 34 packets muxed (1692057600 bytes); 
[2019-11-19 06:56:26.810320] INFO: slash:   Total: 34 packets (1692057600 bytes) muxed
[2019-11-19 06:56:26.847195] INFO: slash: [AVIOContext @ 0x55d30063dc00] Statistics: 0 seeks, 6455 writeouts
[2019-11-19 06:56:26.847378] INFO: slash: [AVIOContext @ 0x55d30063f080] Statistics: 5311738 bytes read, 0 seeks
[2019-11-19 06:56:26.885826] NOTICE: slash: DETAIL: time(ffmpeg:2) = 3.3977s
[2019-11-19 06:56:28.373194] NOTICE: slash: DETAIL: time(psnr:1) = 1.4866s
[2019-11-19 06:56:28.480388] TRACE: slash.core.error: Error added: ValueError: ('cannot reshape array of size 0 into shape (4320,7680)', 'frame 34/50')
  /opt/media/src/vaapi-fits-full/full, line 41:
      sys.exit(main())
  /opt/media/src/vaapi-fits-full/full, line 38:
      return main_entry_point()
  /usr/local/lib/python2.7/dist-packages/slash/core/fixtures/parameters.py, line 34:
                    return func(*args, **kwargs)
  /opt/media/src/vaapi-fits/test/ffmpeg-qsv/encode/hevc.py, line 48:
        self.encode()
  /opt/media/src/vaapi-fits/test/ffmpeg-qsv/encode/encoder.py, line 163:
          self.check_metrics()
  /opt/media/src/vaapi-fits/test/ffmpeg-qsv/encode/encoder.py, line 187:
            self.frames, self.format),
  /opt/media/src/vaapi-fits/lib/common.py, line 33:
            ret = function(*args, **kwargs)
  /opt/media/src/vaapi-fits/lib/metrics.py, line 149:
        nframes, __compare_psnr)
  /opt/media/src/vaapi-fits/lib/metrics.py, line 119:
            y2, u2, v2 = file2.next_frame()
  /opt/media/src/vaapi-fits/lib/metrics.py, line 64:
          return self.reader(self.fd, self.width, self.height)
  /opt/media/src/vaapi-fits/lib/framereader.py, line 46:
      y = numpy.fromfile(fd, dtype=numpy.uint8, count=size).reshape((height, width))

**Comment by uartie** [comment]
why do you think this is a vaapi-fits bug?  You're test configuration set "frames=50", which instructs the test case to "expect" 50 frames in psnr calculation.

**Comment by uartie** [comment]
The error shows that it only found 34 frames.

**Comment by uartie** [comment]
> why do you think this is a vaapi-fits bug? Your test configuration set "frames=50", which instructs the test case to "expect" 50 frames in psnr calculation.

More specifically, frames=50 in encode test case configuration instructs the test to encode 50 frames from source yuv file, then decode 50 frames of that result, then calculate psnr on 50 frames.  According to your output, ffmpeg only encoded 34 frames.  Why?  Either the source yuv file contains less then 50 frames (i.e. 34 frames) or there is a bug in ffmpeg encoder.  Please confirm

**Comment by uartie** [comment]
or maybe the decoder dropped a bunch of frames?

**Comment by uartie** [comment]
How many frames does yamidecode report for the file encoded by ffmpeg?

**Comment by FocusLuo** [comment]
To use ffmpeg SW, ffmpeg-vaapi or yamidecode to do the decode, they can dump 50frames with sample md5check; but to use sample_decode/ffmpeg-vaapi/ffmpeg-qsv, only can dump 34 frames; 
It seems like that there is issue in ffmpeg-qsv decode
root@media_libva_icl2:/home/focus/workspace_focus/vaapi-fits-full# md5sum test_8k-ffmpeg-hw.yuv test_8k_ffmpeg-sw.yuv yamidump.yuv
5e1e72a4b3b171359bd02c48fedc9b91  test_8k-ffmpeg-hw.yuv
5e1e72a4b3b171359bd02c48fedc9b91  test_8k_ffmpeg-sw.yuv
5e1e72a4b3b171359bd02c48fedc9b91  yamidump.yuv

**Comment by uartie** [comment]
ok, then it's not a test issue.  it's a ffmpeg bug.
