### ISSUE TITLE
enhancement: multi-resolution stream SSIM/PSNR value calculation

### ISSUE THREAD

**Issue by wangzj0601** [intel/vaapi-fits#15]
we should support multi-resolution stream SSIM/PSNR value calculation

**Comment by uartie** [comment]
Same question as in https://github.com/intel/vaapi-fits/issues/14#issuecomment-466230237

**Comment by wangzj0601** [comment]
for gstreamer, the input streamer is mul-resolution, the output should be mul-resolution too, so to calculate the output ssim, we should support multi-resolution stream SSIM/PSNR value calculation.

we can set case as below, I will implement it later.
mul_res = [(width1, height1, frame1), (width2, height2, frame2),...]

function:
for i in mul_res:
  for j in range(i[2]):
    ...
    ...

**Comment by wangzj0601** [comment]
for psnr, the encoded file is specified as NxM resolution in general, so we can ignore multi-resolution psnr calculation at now.

**Comment by wangzj0601** [comment]
@uartie  can you help have a review about https://github.com/intel/vaapi-fits/pull/24

**Comment by wangzj0601** [comment]
now gstreamer add parse "videoscale" to make the output as single resolution, so no need multi-res ssim support, close it
