### ISSUE TITLE
enhancement: CSC tests support

### ISSUE THREAD

**Issue by wangzj0601** [intel/vaapi-fits#16]
we should enable scripts to test csc on gst/ffmpeg

**Comment by uartie** [comment]
We already have a CSC test in test/gst-vaapi/vpp/csc.py.  Although, this test only works for yuv CSC when both input and output have the same pixel subsampling (e.g. NV12 -> I420 are both 4:2:0 subsample).  So we still need to investigate how we want to support other kinds of CSC testing (4:4:4 -> 4:2:0 for example).

We still need to figure out how to do CSC pipelines with the other components

**Comment by wangzj0601** [comment]
Yes, you are right
