### ISSUE TITLE
Remove P210 and P410 formats

### ISSUE THREAD

**Issue by uartie** [intel/vaapi-fits#167]
According to https://docs.microsoft.com/en-us/windows/win32/medfound/10-bit-and-16-bit-yuv-video-formats#p216-and-p210, P210 is 2 planes (Y plane + interleaved UV plane and each sample is stored as a WORD.  There is no definition for P410, but one would assume it follows the same pattern.

Unfortunately, P210 and P410 in vaapi-fits are implemented incorrectly as 3 planes (Y plane + U plane + V plane).  And, AFAICT, ffmpeg and gstreamer do not have appropriate formats to handle the official P210 and unofficial P410 formats.

Fortunately, #164 and #163 will add support for Y210 and Y410 which have better support across the media SW stacks (drivers & middleware).  Once these patches are approved and merged, we should remove P210 and P410 code and tests in vaapi-fits.

**Comment by uartie** [comment]
BTW, ffmpeg Y210 and Y410 support are still pending:

https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=102
https://patchwork.ffmpeg.org/project/ffmpeg/patch/1575470593-7732-1-git-send-email-linjie.fu@intel.com/

Regardless, we don't need to wait for those patches to be accpeted and should proceed with removing P210 and P410 here.

**Comment by FocusLuo** [comment]
Sure, I will

**Comment by uartie** [comment]
#169 #174
