### ISSUE TITLE
Please mention supported architectures in README

### ISSUE THREAD

**Issue by stefanct** [intel/vaapi-fits#168]
It would have been nice to know that this software does not support my system before wasting my time... (yet it's old). The reference to the `caps` directory is way too hidden to suffice in that circumstance.

**Comment by uartie** [comment]
The README instructs users to look in `lib/caps` for supported platforms/drivers.  It is not efficient to also maintain a list of platforms in the README when we can just point you to that directory.

https://github.com/intel/vaapi-fits#some-useful-options

If these instructions aren't clear/visible enough, then please propose a patch.

If you need special caps for your platform, then write a caps file and place it in that directory.  Also, maybe you could put in a request/patch to add support for "user-defined" caps to be loaded externally.

Also, there is nothing stopping the user from using any of the caps on any platform... even if it doesn't match you platform.  Just don't expect every test to pass.
