### ISSUE TITLE
Transcoding feature support

### ISSUE THREAD

**Issue by haribommi** [intel/vaapi-fits#5]
following transcoding  features validation can be added as an enhancements to vaapi-fits.

1. Transcoding  AVC test streams to AVC, HEVC, MPEG2 and MJPEG using HW decode->HW encode, HW decode->SW encode ,SW decode ->HW encode.
2. Transcoding  HEVC test streams to AVC, HEVC, MPEG2 and MJPEG using HW decode->HW encode, HW decode->SW encode ,SW decode ->HW encode.
3. Transcoding  MPEG2 test streams to AVC, HEVC, MPEG2 and MJPEG using HW decode->HW encode
4. Transcoding  VC1 test streams to AVC, HEVC, MPEG2 and MJPEG using HW decode->HW encode.

**Comment by wangzj0601** [comment]
@haribommi,  have implement it on ffmpeg/gstreamer, can you have a verification and close it?

**Comment by haribommi** [comment]
Implemented this feature with following patches:
https://github.com/intel/vaapi-fits/pull/17
https://github.com/intel/vaapi-fits/pull/34
https://github.com/intel/vaapi-fits/pull/39
