### ISSUE TITLE
Does ffmpeg test need change to use before  scaler to calculate md5  in vp9_10bit decode?

### ISSUE THREAD

**Issue by zhuqingliang** [intel/vaapi-fits#96]
After this https://patchwork.ffmpeg.org/patch/13883/ , https://github.com/intel-media-ci/ffmpeg/pull/58 apply  , ffmpeg-vaapi got same md5 as gst-vaapi , and passrate hit 98.5% . does ffmpeg test case need to change command line ? such as:
 
call(
  "ffmpeg -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD128 "
  " -filter_hw_device hw -v verbose -i {source} "
  " -vf rawdump=file={decoded} "
  " -pix_fmt p010le -vsync passthrough -f null  -".format(**vars(self)))

**Comment by uartie** [comment]
I don't think the rawdump patch will be accepted, which is fine.  The FFmpeg dev community has responded with existing options to achieve the same result.  In particular, either `-reinit_filter 0` or the `split` filter can give us unscaled raw output.  I have tried the former, but not the latter.  Either way, yes we will need to change the ffmpeg command line we use in our tests depending on which method works best for testing.

**Comment by zhuqingliang** [comment]
No need to change commandline anymore , so close it.
